/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  i18n: {
    defaultLocale: "en",
    // supported locales defined in `i18n.config.json`
    locales: [
      "ar",
      "az",
      "bg",
      "bn",
      "ca",
      "cs",
      "da",
      "de",
      "el",
      "en",
      "es",
      "fa",
      "fi",
      "fil",
      "fr",
      "gl",
      "gu",
      "he",
      "hi",
      "hr",
      "hu",
      "id",
      "ig",
      "it",
      "ja",
      "ka",
      "kk",
      "km",
      "ko",
      "lt",
      "ml",
      "mr",
      "ms",
      "nb",
      "nl",
      "pcm",
      "pl",
      "pt",
      "pt-br",
      "ro",
      "ru",
      "se",
      "sk",
      "sl",
      "sr",
      "sw",
      "ta",
      "th",
      "tr",
      "uk",
      "ur",
      "uz",
      "vi",
      "zh",
      "zh-tw",
    ],
  },
  // This option could be enabled in the future when flagged as stable, to speed up builds
  // (see https://nextjs.org/docs/pages/building-your-application/configuring/mdx#using-the-rust-based-mdx-compiler-experimental)
  // experimental: {
  //   mdxRs: true,
  // },
}
