name: Quality

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs: 
  eslint: 
    # Executes `lint:fix` to clean up errors or 
    # warnings that are autofixable.
    # Also posts warnings or errors that are not autofixable.
    name: Eslint Fix
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install deps
        run: yarn
      
      - name: Run ESLint Fix
        run: yarn lint:fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: run lint:fix'


